apiVersion: v1
kind: Service
metadata:
  name: hello-k8s
  labels:
    app: hello-service
spec:
  type: NodePort
  selector:
    app: hello-pod
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30500